### ISSUE TITLE
Reading data from the cloud... not successful

### ISSUE THREAD

**Issue by NoPlayBack** [sarnau/MMMMobileAlerts#52]
Hi there,

i was trying to make use from your documentation here:
https://github.com/sarnau/MMMMobileAlerts/blob/master/MobileAlertsGatewayApplicationAPI.markdown
as far as i understand there is the possibility to fetch sensor data from all available sensors with this interface?
Did try to use that code within Python, and did run into some issues:

"request += '&timestamp=%s' % datetime.datetime.utcnow().strftime("%s")	# current UTC timestamp"
seems as if %s formating code is not valid any more? Did use
"request += '&timestamp=%s' % datetime.datetime.utcnow().timestamp()"
instead.

Not sure where to place my sensor ids... should they be listed in sensors = [] ???

Also not sure how to work with UUID, where can i find more information about this?

Trying to run that code but the result was "errorcode 1051, The request parameters are invalid"

Is this (creating an issue) the correct way to ask questions or is there a community somewhere which i can contact to get some help here?

**Comment by monojk** [comment]
I also have a problem reading the data, always getting a timeout. Does the server still support these queries?
```
payload is:
devicetoken=empty&vendorid=BE60BB85-EAC9-4C5B-8885-1A54A9D51E29&phoneid=Unknown&version=1.21&build=248&executable=Mobile Alerts&bundle=de.synertronixx.remotemonitor&lang=en&timezoneoffset=60&timeampm=true&usecelsius=true&usemm=true&speedunit=0&timestamp=1728737523&requesttoken=ba5e956d4832515f0b26c97f08539185&deviceids=0836C6E3AF5E

Traceback (most recent call last):
  File "/home/pi/./getMobileAlertsData.py", line 56, in <module>
    conn.request("POST", "/api/v1/dashboard", payload, headers)
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

```

**Comment by NoPlayBack** [comment]
I finally made it to get the data, and i am using python and requests to receive data from all sensors i have.
Using this:
r = requests.post('https://www.data199.com/api/pv1/device/lastmeasurement', data={"deviceids": id_list, "phoneid": '123456789123'}, timeout=60).json()
The id_list is a string with all sensor-ids separated by a comma, like this:
'031234567897,041234567897,035454545454,049876546589,'

**Comment by monojk** [comment]
I use that also for normal sensors. But with the rain sensor, the data is the accumulated rain since the start of using that device.

I want to get the current rain data which is a delta of the last measurements. That data is there https://measurements.mobile-alerts.eu/ available in the browser (firefox or chrome) with security off because the https certificate of that server expired last Friday. And with python code I can't access the webpage. 

Any idea how to access the http webpage `measurements.mobile-alerts.eu` instead of https with python? 

With   `conn = http.client.HTTPSConnection(url)` I get
```
  File "/usr/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)
```

With `conn = http.client.HTTPConnection(url)` I get
```
301 Moved Permanently
```

**Comment by Themanwithoutaplan** [comment]
> I use that also for normal sensors. But with the rain sensor, the data is the accumulated rain since the start of using that device.
> 
> I want to get the current rain data which is a delta of the last measurements. That data is there https://measurements.mobile-alerts.eu/ available in the browser (firefox or chrome) with security off because the https certificate of that server expired last Friday. And with python code I can't access the webpage.
> 
> Any idea how to access the http webpage `measurements.mobile-alerts.eu` instead of https with python?
> 
> With `conn = http.client.HTTPSConnection(url)` I get
> 
> ```
>   File "/usr/lib/python3.11/ssl.py", line 1379, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)
> ```
> 
> With `conn = http.client.HTTPConnection(url)` I get
> 
> ```
> 301 Moved Permanently
> ```

For talking to HTTP servers in Python, it's usually best just to use the [requests](https://requests.readthedocs.io/en/latest/) library. Several generations of the code in the standard library have failed to provide an easy use API that handles all the weird stuff you don't know you need. Requests fixes this.

When talking to the mobile-alerts server directly, you'll also need to initate the connection in a session – `s = requests.Session()` with some headers including a user agent and your "phoneid".

**Comment by Themanwithoutaplan** [comment]
It looks like the URLs for the service have changed: you now need HTTPs and the port has changed. However, even then requests are rejected because of the domain name: `"errormessage": "The request parameters are are invalid",\r\n  "primarydomain": "www.data199.com"`. You don't get the error when getting the last measurement, but the port suggests that a different server may be involved.

According to EU law, Mobile Alerts is now obliged to provide all the data from such sensors, but they don't seem to respond to requests to do so.

**Comment by sarnau** [comment]
They might have to provide data. If so, you need to prove your identity, then it can take up 1 month and you might receive an email with a URL to a ZIP file with the data. That is not really viable. They might also argue that this is not personal information anyway and just ignore you…

The best way to deal with these is to intercept the bridge and keep the data local.

**Comment by Themanwithoutaplan** [comment]
Actually, according to EU law since 2024 all such service must provide APIs for the data and the existing one that only provides the last measurement is insufficient. 

I now scrape the sensor data directly from the [measurements site](https://measurements.mobile-alerts.eu/)

**Comment by NoPlayBack** [comment]
how do you do that ?

**Comment by Themanwithoutaplan** [comment]
I've written a little Python script for it. You need to create a session that looks like a browser using the requests library with your phoneid:

```python
    first = f"https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid={PHONEID}"
    headers = {"User-Agent":
	"Mozilla/5.0"}
    s = requests.Session()
    s.headers = headers

    data = {
        "deviceid":device,
        "vendorid":"a3448f31-17f1-4093-bda9-c0d93170ef02",
        "appbundle":"eu.mobile_alerts.weatherhub",
        "fromepoch":int(from_epoch.timestamp()),
        "toepoch":int(to_epoch.timestamp()),
    }
    second = "https://measurements.mobile-alerts.eu/Home/MeasurementDetails"
    r = s.get(second, params=data)
    html = r.text
```

Then you parse the HTML (I use BeautifulSoup for this) to get the data for your processing. You can get up to the last three months data, which is better than nothing and after that it's pretty easy to keep up to date.

**Comment by NoPlayBack** [comment]
Well.... i see Response 200

Have modified:
first = f"https://measurements.mobile-alerts.eu/Home/SensorsOverview?phoneid=123456789012

and

    data = {
        "deviceid":"1234567879012", #ID of device as shown on Overviewpage

        "vendorid":"a3448f31-17f1-4093-bda9-c0d93170ef02",

        "appbundle":"eu.mobile_alerts.weatherhub",

        "fromepoch":1768038009, #changed to UTC as my machine does not know from_epoch

        "toepoch":1770716409, #changed to UTC as my machine does not know from_epoch

what i see is that "first" (including the phoneid) is not used anywhere ?

What am i doing wrong ?

**Comment by NoPlayBack** [comment]
...ups ... forgot to mention.... my html is empty after 
`html = r.text`

**Comment by Themanwithoutaplan** [comment]
Have you tried in a browser? You might not need the phone id at all: I think I initially used the first URL to get a session with the phone id but that doesn't seem to be necessary. Just try `f"https://measurements.mobile-alerts.eu/Home/MeasurementDetails?deviceid={device_id}&vendorid=a3448f31-17f1-4093-bda9-c0d93170ef02&appbundle=eu.mobile_alerts.weatherhub"` in a browser with one of your device ids and not the phone id.

**Comment by NoPlayBack** [comment]
Nop....blank screen.
but i did now select my overview page and device page via my normal way and i recognize that my vendorid is different, and that the appbundle=eu.mobile_alerts.mobilealerts.
Using these 2 new values i see the html.
So...

1. do you know more background on this?
2. Thanks !!!!!

**Comment by Themanwithoutaplan** [comment]
Then use that vendor id. The script here says that the vendor id doesn't matter for the API call but it seems to matter here. I think it relates to the "vendor id" of the app on your phone as a minimal kind of security.
